(source gnu)
(source melpa)
(source org)

(depends-on "epl")
(depends-on "ace-jump-mode")
(depends-on "ag")
(depends-on "auto-compile")
(depends-on "better-defaults")
(depends-on "buffer-move")
(depends-on "company")
(depends-on "company-cider")
(depends-on "company-go")
(depends-on "deft")
(depends-on "diff-hl")
(depends-on "dired+")
(depends-on "doremi")
(depends-on "exec-path-from-shell")
(depends-on "faces+")
(depends-on "facemenu+")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "flycheck-tip")
(depends-on "git-gutter-fringe+")
(depends-on "guide-key")
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "helm-flycheck")
(depends-on "helm-descbinds")
(depends-on "helm-package")
(depends-on "key-chord")
(depends-on "magit")
(depends-on "markup-faces")
;;(depends-on "mic-paren")
(depends-on "org")
(depends-on "org-pomodoro")
(depends-on "org-trello")
;;(depends-on "pallet")
(depends-on "popwin")
(depends-on "popup")
(depends-on "pos-tip")
(depends-on "powerline")
(depends-on "projectile")
(depends-on "rainbow-delimiters")
(depends-on "rainbow-mode")
(depends-on "refheap")
(depends-on "sass-mode")
(depends-on "smartparens")
(depends-on "smooth-scrolling")
(depends-on "sr-speedbar")
(depends-on "twittering-mode")
(depends-on "undo-tree")
(depends-on "window-number")
(depends-on "winpoint")
(depends-on "yaml-mode")
(depends-on "yasnippet")
(depends-on "volatile-highlights")
(depends-on "eval-sexp-fu")

;; modes

;; Clojure
(depends-on "cider")
(depends-on "clojure-test-mode")
(depends-on "clojure-mode")


;; adoc
(depends-on "adoc-mode")

;; ocaml
(depends-on "tuareg")
(depends-on "merlin")

;; erlang
(depends-on "erlang")
